---
app_name: JDK 7 Update 79
app_name_pretty: Java
app_url: "http://download.oracle.com/otn-pub/java/jdk/7u79-b15/jdk-7u79-macosx-x64.dmg"
installer_type: pkg
install_method: dmg
install_target: "/"
mount_path: /Volumes/JDK 7 Update 79/
download_url_headers: "Cookie: oraclelicense=accept-securebackup-cookie"
