---
- name: ensure that GPG key for RVM is installed
  #command: gpg --keyserver hkp://pgp.mit.edu --keyserver-options timeout=120 --recv-keys 409B6B1796C275462A1703113804BB82D39DC0E3
  #command: 'curl -sSL https://rvm.io/mpapis.asc | gpg --import -'
  shell: curl -sSL https://rvm.io/mpapis.asc | gpg --import -
  sudo: yes
  sudo_user: '{{ user }}'
  when: ansible_os_family != 'Darwin'

- name: Install RVM
  shell: \curl -L https://get.rvm.io | bash -s stable --autolibs=3 creates={{ HOME }}/.rvm/bin/rvm
  sudo: yes
  sudo_user: '{{ user }}'

- name: Add RVM to shell profile
  lineinfile:
    dest={{ HOME }}/{{ shellrc }}
    state=present
    create=yes
    line='[[ -s "{{ HOME }}/.rvm/scripts/rvm" ]] && source "{{ HOME }}/.rvm/scripts/rvm"'
  sudo: yes
  sudo_user: '{{ user }}'

- name: RVM Reload
  shell: "{{ HOME }}/.rvm/bin/rvm reload"
  sudo: yes
  sudo_user: '{{ user }}'

- name: RVM Requirements for user  {{ user }}
  shell: "{{ HOME }}/.rvm/bin/rvm requirements"
  sudo: yes
  when: ansible_os_family == "Debian"

- name: RVM Requirements for user  {{ user }}
  shell: "{{ HOME }}/.rvm/bin/rvm requirements"
  sudo: yes
  sudo_user: '{{ user }}'
  when: ansible_os_family == "Darwin"

- name: Install Ruby
  shell: "{{ HOME }}/.rvm/bin/rvm install {{ ruby }} creates={{HOME}}/.rvm/rubies/{{ ruby }} --default"
  register: shell_output
  sudo: yes
  sudo_user: '{{ user }}'

- name: Update ssl certs
  command: bash -lc "{{ HOME }}/.rvm/bin/rvm osx-ssl-certs update"
  sudo: yes
  sudo_user: '{{ user }}'
  when: ansible_os_family == "Darwin"

- name: Install bundler
  command:  bash -lc "{{ HOME }}/.rvm/bin/rvm @global do gem install bundler" creates={{ HOME }}/.rvm/gems/{{ ruby }}@global/bin/bundle
  sudo: yes
  sudo_user: '{{ user }}'