---
- name: Download {{ app_name_pretty }} with custom download headers
  get_url: "url={{ app_url }} dest='{{ downloads }}/{{ app_name }}.dmg' timeout=3000 headers='{{ download_url_headers }}'"
  when: download_url_headers is defined
- name: Download {{ app_name_pretty }}
  get_url: "url={{ app_url }} dest='{{ downloads }}/{{ app_name }}.dmg' timeout=3000"
  when: download_url_headers is undefined
- name: Mount {{ app_name_pretty }} image
  command: hdiutil attach '{{ app_name }}.dmg' chdir='{{ downloads }}'
- name: Remove existing app if present
  file: path='/Applications/{{ app_name }}.app' state=absent
  when: installer_type == 'app'
- name: Copy {{ app_name_pretty }} app to Applications directory
  command: cp -R '{{ mount_path}}{{ app_name }}.app' /Applications
  when: installer_type == 'app'
- name: Install {{ app_name_pretty }} pkg
  command: installer -package '{{ mount_path }}{{ app_name }}.pkg' -target '{{ install_target }}'
  when: installer_type == 'pkg'
  sudo: yes
- name: Install {{ app_name_pretty }} mpkg
  command: installer -package '{{ mount_path }}{{ app_name }}.mpkg' -target '{{ install_target }}'
  when: installer_type == 'mpkg'
  sudo: yes
- name: Unmount {{ app_name_pretty }} image
  command: hdiutil detach '{{ mount_path }}'
